Repository Roshansuthar1105/Omex, pull requests merged in 2025-09, with the labels that each got.

#156 Updated drop down for both of them i.e for Tool and Compony
  Frontend/src/components/Navbar.jsx
Labels: bug, gssoc25, Level 2

#173 Replace Twitter icon with BsTwitterX in Footer component
  Frontend/src/components/Footer.jsx
Labels: bug, gssoc25, Level 1

#175 Add Omex logos and optimize UI sizing across components
  Frontend/public/README-logo.md
  Frontend/public/logo-guidelines.md
  Frontend/public/omex-favicon.svg
  Frontend/public/omex-icon.svg
  Frontend/public/omex-logo-mono.svg
  Frontend/public/omex-logo-transparent.svg
  Frontend/public/omex-logo-white.svg
  Frontend/public/omex-logo.svg
  Frontend/public/omex-text-logo-white.svg
  Frontend/public/omex-text-logo.svg
  Frontend/src/App.jsx
  Frontend/src/components/ChatComponent.jsx
  Frontend/src/components/Footer.jsx
  Frontend/src/components/Navbar.jsx
  Frontend/src/pages/FAQ.jsx
  Frontend/src/pages/Home.jsx
  Frontend/src/pages/LogoShowcase.css
  Frontend/src/pages/LogoShowcase.jsx
  c/Users/Gupta/Downloads/GSSOC-Omex/Frontend/public/omex-logo.svg
  package-lock.json
  package.json
Labels: enhancement, gssoc25, Level 3

#182 Added example code for the 5 features
  Frontend/src/pages/CodeBeautifier.jsx
  Frontend/src/pages/ErrorDebugger.jsx
  Frontend/src/pages/PerformanceAnalyzer.jsx
  Frontend/src/pages/SecurityScanner.jsx
  Frontend/src/pages/TestCaseGenerator.jsx
Labels: enhancement, gssoc25, Level 3

#197 New Tool Dependency Scanner
  BackEnd/src/app.js
  BackEnd/src/config/systemInstructions.js
  BackEnd/src/controllers/ai.controller.js
  BackEnd/src/routes/ai.routes.js
  BackEnd/src/services/ai.service.js
  Frontend/src/App.jsx
  Frontend/src/components/Loader.jsx
  Frontend/src/components/Nav.jsx
  Frontend/src/components/Navbar.jsx
  Frontend/src/components/css/Loader.css
  Frontend/src/components/css/NavBar.css
  Frontend/src/pages/CodeTools.jsx
  Frontend/src/pages/DependencyScanner.jsx
  Frontend/src/pages/Home.jsx
Labels: enhancement, gssoc25, Level 3

#188 Refactor ai.controller.js to reduce boilerplate with centralized request handling
  BackEnd/src/controllers/ai.controller.js
Labels: enhancement, gssoc25, Level 3

#255 ✨ updated the folder structre in readme.md
  README.md
Labels: enhancement, gssoc25, Level 2
