Repository Roshansuthar1105/Omex, pull requests merged in 2025-08, with the labels that each got.

#62 Added the cursor-pointer feature to Tools and Company
  Frontend/src/components/Nav.jsx
Labels: enhancement, Style Enhancement, gssoc25, Level 1

#65 fix: correct spelling of "Summarize" to "Summarizer" in Home component
  Frontend/src/pages/Home.jsx
Labels: bug, good first issue, gssoc25, Level 1

#70 added responsive FAQ section
  Frontend/src/components/Faq.jsx
  Frontend/src/pages/Home.jsx
Labels: enhancement, good first issue, gssoc25, Level 2

#85 Added the new Loader
  Frontend/src/components/Loader.jsx
Labels: enhancement, Style Enhancement, gssoc25, Level 3

#75 Make website name clickable to redirect to home page
  .DS_Store
  Frontend/src/components/Nav.jsx
Labels: enhancement, good first issue, gssoc25, Level 1

#93 No Duplicates of New Code Tools Section
  Frontend/src/pages/Home.jsx
Labels: bug, gssoc25, Level 2

#96 Navbar enhanced
  Frontend/src/components/Navbar.jsx
Labels: enhancement, gssoc25, Level 3

#97 Increased Navbar Title Font Size
  Frontend/src/components/Navbar.jsx
Labels: enhancement, good first issue, gssoc25, Level 1

#99 fix: Remove unnecessary introductory text in optimization output
  BackEnd/src/services/ai.service.js
  Frontend/package-lock.json
  Frontend/package.json
Labels: bug, gssoc25, Level 2

#129 Enhanced the UI of contact Us page
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/pages/Contact.jsx
Labels: enhancement, gssoc25, Level 3

#141 Added Real-Time Leaderboard with Search & Pagination
  Frontend/src/components/ContributorsLeaderboard.jsx
Labels: enhancement, gssoc25, Level 3
